Code cleanup: Replaced echo with printf.

diff --git a/src/bashrun b/src/bashrun
--- a/src/bashrun
+++ b/src/bashrun
@@ -34,7 +34,7 @@ source __PREFIX__/share/bashrun/globals
 # check if another frontend process is currently running
 lock="$bashrun_cache_home/bashrun.lck"
 if [[ -f "$lock" ]]; then
-    echo "bashrun: locked: $bashrun_cache_home/bashrun.lck exists." >&2
+    printf '%s\n' "bashrun: locked: $bashrun_cache_home/bashrun.lck exists." >&2
     exit 1
 fi
 
@@ -82,7 +82,7 @@ until [[ "$1" == "--" || "${1:0:1}" != '-' ]]; do
 	    exit 0
 	    ;;	
 	*)
-	    echo "bashrun: error: unknown option: $1" >&2
+	    printf '%s\n' "bashrun: error: unknown option: $1" >&2
 	    usage
 	    exit 1
 	    ;;
@@ -157,17 +157,17 @@ case "$command" in
 	§window.toggle_smart &>/dev/null
 	;;
     wid)
-	echo "$wid"
+	printf '%s\n' "$wid"
 	;;
     pid)
-	echo "$pid"
+	printf '%s\n' "$pid"
 	;;
     su)
 	if [[ ${#args[@]} -gt 0 ]]; then
 	    remote su-run "${args[@]}"
 	else
-	    echo "bashrun: error: command \`su' requires at least " \
-		"one argument: <cmd>" >&2
+	    printf '%s\n' \
+		"bashrun: error: command \`su' requires at least one argument: <cmd>" >&2
 	    exit 1
 	fi
 	;;
@@ -175,8 +175,8 @@ case "$command" in
 	if [[ ${#args[@]} -gt 0 ]]; then
 	    remote "${args[@]}"
 	else
-	    echo "bashrun: error: command \`do' requires at least " \
-		"one argument: <action> [<cmd>]" >&2
+	    printf '%s\n' \
+		"bashrun: error: command \`do' requires at least one argument: <action> [<cmd>]" >&2
 	    exit 1
 	fi
 	;;
@@ -197,7 +197,7 @@ case "$command" in
 	remote quit
 	;;    
     *)
-	echo "bashrun: error: unknown command: $command" >&2
+	printf '%s\n' "bashrun: error: unknown command: $command" >&2
 	exit 1
 esac 
 exit 0
diff --git a/src/utils b/src/utils
--- a/src/utils
+++ b/src/utils
@@ -29,7 +29,7 @@ function §function.exported? () {
 }	
 
 function §function.code {
-    echo "$(type $1 | sed '1 d')"
+    printf '%s\n' "$(type $1 | sed '1 d')"
 }
 
 function §function.clone {
@@ -37,12 +37,12 @@ function §function.clone {
     local function="$1"
     local newname="$2"
 
-    if $(type -t $function &> /dev/null); then
-	local code="$(echo -n '#'; type $function)"
+    if $(type -t "$function" &> /dev/null); then
+	local code="$(§function.code "$function")"
 	code="${code/$function \(\)/$newname ()}"
 	eval "$code"
     else
-	echo "§function.clone: error: no such function: $function"
+	printf '%s\n' "§function.clone: error: no such function: $function"
     fi
 }
 
@@ -85,7 +85,7 @@ function §interpolate {
 	str=${str/\$$var/$val}
     done
     str=${str//__DoLlArSiGn__/\$}
-    echo "$str"
+    printf '%s\n' "$str"
 }
 
 function §replace {
@@ -121,7 +121,7 @@ function §replace {
 	fi
 	prev="$char"
     done
-    echo "$result"
+    printf '%s' "$result"
 }
 
 function §debug {
@@ -176,9 +176,9 @@ function §debug {
     esac
     
     if [[ bashrun_debug_action -eq 1 ]]; then
-	echo -ne "$col$_from$n $d" >&2
+	printf '%b' "$col$_from$n $d" >&2
     else
-	echo -ne "$col$_func$n $d" >&2
+	printf '%b' "$col$_func$n $d" >&2
     fi
 
     local str=''
@@ -188,16 +188,15 @@ function §debug {
 	
 	if [[ "${str:0:1}" == "-" && "$str" != "->" ]]; then # color option
 	    col="${str:1:1}"
-	    echo -ne "${!col}" >&2
+	    printf '%b' "${!col}" >&2
 	    requested=1
-
 	else
-	    [[ requested -eq 0 ]] && echo -ne "$d" >&2 
-	    echo -n "$str " >&2
+	    [[ requested -eq 0 ]] && printf '%b' "$d" >&2 
+	    printf '%b' "$str " >&2
 	    requested=0
 	fi
     done
-    echo -e "$n" >&2
+    printf '%b\n' "$n" >&2
 }
 
 function §separator {
@@ -223,18 +222,18 @@ function §separator {
     local title=$1
     local width=${2:-$COLUMNS}
     
-    echo -ne "$b" >&2
+    printf '%b' "$b" >&2
     if [[ "$title" != '' ]]; then
 	(( width = width - ${#title} - 4 )) 
-	echo -ne "$prefix $y$title$b " >&2
+	printf '%b' "$prefix $y$title$b " >&2
     fi
     
     local i=0;
     for (( i=1; i<=$width; i++ )); do
-	echo -n "-" >&1
+	printf '%s' "-" >&1
     done
     
-    echo -e "$n" >&2
+    printf '%b' "$n" >&2
 }
 
 function §prepare_logfile {
@@ -261,7 +260,7 @@ function §ks2kn {
     local keyseq=$1
 
     if §keynames.seek "$keyseq"; then
-	echo $(§keyname.get_name)
+	printf '%s' "$(§keyname.get_name)"
 	return 0
     fi
 
@@ -278,25 +277,7 @@ function §ks2kn {
     if [[ "$keyname" =~ [a-zA-z]$enter ]]; then
 	keyname=${keyname/$enter/-$enter}
     fi
-    echo "$keyname"
-}
-
-function §print_line {
-
-    local title=$1
-    local char=${2:--}
-    local width=${3:-$COLUMNS}
-    local i;
-
-    if [[ "$title" != '' ]]; then
-	(( width = width - ${#title} - 4 )) 
-	echo -n "$char$char $title "
-    fi
-
-    for((i=0; i<$width; i++)); do
-	echo -n $char
-    done
-    echo
+    printf '%s' "$keyname"
 }
 
 function §print_bindings {
@@ -323,7 +304,7 @@ function §print_bindings {
 	ids="$(§bindings.select keymap "$keymap")"
 	[[ -z "$ids" ]] && continue
 
-	echo -e "${w}Bashrun Keybindings$n ($c$mode$n):\n"
+	printf '%b' "${w}Bashrun Keybindings$n ($c$mode$n):\n\n"
 
 	covered=""
 
@@ -336,16 +317,16 @@ function §print_bindings {
 		keyname="$(§binding.get_keyname)"
 		[[ " $covered " =~ " $keyname " ]] && continue
 			
-		echo -en "\t$b$keyname$n\t"
-		echo -en "$(§interpolate "$(§action.get_description)")"
+		printf '%b' "\t$b$keyname$n\t"
+		printf '%b' "$(§interpolate "$(§action.get_description)")"
 		if [[ -n "$(§action.get_depends)" ]]; then
-    		    echo -en " ($(§action.print_depends))"
+    		    printf '%b' " ($(§action.print_depends))"
 		fi
-		echo
+		printf '\n'
 		covered+="$keyname "
 	    fi
 	done
-	echo
+	printf '\n'
     done	
 }
 
@@ -353,5 +334,5 @@ function §tilde_path {
     # replace $HOME with a tilde for printing
     local path="$1"
     path=${path/$HOME/\~}
-    echo "$path"
+    printf '%s' "$path"
 }
